### ISSUE TITLE
关于 ios端 引入 插件跑不起来，提示CocoaPods 过时（已经是1.91）

### ISSUE THREAD

**Issue by yuefeng007** [JiangJuHong/FlutterTencentImPlugin#5]
如题，log日志如下

```
bogon:demo a$ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              0.8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A tencent_im_plugin
      - Flutter
      - amap_core_fluttify
      - amap_location_fluttify
      - city_pickers
      - flutter_plugin_android_lifecycle
      - flutter_sound
      - flutter_splash_screen
      - fluttertoast
      - foundation_fluttify
      - image_crop
      - image_picker
      - path_provider
      - path_provider_macos
      - permission_handler
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web
      - webview_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `amap_core_fluttify` from
    `.symlinks/plugins/amap_core_fluttify/ios`
    -> Fetching podspec for `amap_location_fluttify` from
    `.symlinks/plugins/amap_location_fluttify/ios`
    -> Fetching podspec for `city_pickers` from
    `.symlinks/plugins/city_pickers/ios`
    -> Fetching podspec for `flutter_plugin_android_lifecycle` from
    `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
    -> Fetching podspec for `flutter_sound` from
    `.symlinks/plugins/flutter_sound/ios`
    -> Fetching podspec for `flutter_splash_screen` from
    `.symlinks/plugins/flutter_splash_screen/ios`
    -> Fetching podspec for `fluttertoast` from
    `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `foundation_fluttify` from
    `.symlinks/plugins/foundation_fluttify/ios`
    -> Fetching podspec for `image_crop` from `.symlinks/plugins/image_crop/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from
    `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from
    `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from
    `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `tencent_im_plugin` from
    `.symlinks/plugins/tencent_im_plugin/ios`
    -> Fetching podspec for `webview_flutter` from
    `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_f_f.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/8/f/f/AMapFoundation/1.6.2/AMapFoundation.podspec.json exists!
      Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/0/3/9/AMapLocation/2.6.4/AMapLocation.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_6_1_0.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_8_d_3.txt exists! Returning
      local because checking is only perfomed in repo update
    [!] Unable to find a specification for `HandyJSON` depended upon by
    `tencent_im_plugin`

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or
     with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:389:
    in `find_cached_set'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:
    in `specifications_for_dependency'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:
    in `search_for'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:
    in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:
    in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:
    in `sort_by'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:
    in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif
    ication_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:75
    4:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:74
    6:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:72
    9:in `activate_new_spec'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:68
    6:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:25
    4:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:18
    2:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:i
    n `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:i
    n `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz
    er.rb:1065:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz
    er.rb:1063:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz
    er.rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410
    :in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235
    :in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r
    b:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234
    :in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156
    :in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.
    rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 11 Pro Max.
```

**Comment by yuefeng007** [comment]
pod repo update  解决

**Comment by JiangJuHong** [comment]
你好，请仔细排查 pod install 失败的原因，如果有可能，请提供思路



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 峰硕 <notifications@github.com&gt;
发送时间: 2020年3月16日 23:45
收件人: JiangJuHong/FlutterTencentImPlugin <FlutterTencentImPlugin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[JiangJuHong/FlutterTencentImPlugin] 关于 ios端 引入 插件跑不起来，提示CocoaPods 过时（已经是1.91） (#5)





 
如题，log日志如下
 bogon:demo a$ flutter run Launching lib/main.dart on iPhone 11 Pro Max in debug mode... Running pod install...                                              0.8s CocoaPods' output: ↳       Preparing     Analyzing dependencies     Inspecting targets to integrate       Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)     Finding Podfile changes       A tencent_im_plugin       - Flutter       - amap_core_fluttify       - amap_location_fluttify       - city_pickers       - flutter_plugin_android_lifecycle       - flutter_sound       - flutter_splash_screen       - fluttertoast       - foundation_fluttify       - image_crop       - image_picker       - path_provider       - path_provider_macos       - permission_handler       - shared_preferences       - shared_preferences_macos       - shared_preferences_web       - webview_flutter     Fetching external sources     -&gt; Fetching podspec for `Flutter` from `Flutter`     -&gt; Fetching podspec for `amap_core_fluttify` from     `.symlinks/plugins/amap_core_fluttify/ios`     -&gt; Fetching podspec for `amap_location_fluttify` from     `.symlinks/plugins/amap_location_fluttify/ios`     -&gt; Fetching podspec for `city_pickers` from     `.symlinks/plugins/city_pickers/ios`     -&gt; Fetching podspec for `flutter_plugin_android_lifecycle` from     `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`     -&gt; Fetching podspec for `flutter_sound` from     `.symlinks/plugins/flutter_sound/ios`     -&gt; Fetching podspec for `flutter_splash_screen` from     `.symlinks/plugins/flutter_splash_screen/ios`     -&gt; Fetching podspec for `fluttertoast` from     `.symlinks/plugins/fluttertoast/ios`     -&gt; Fetching podspec for `foundation_fluttify` from     `.symlinks/plugins/foundation_fluttify/ios`     -&gt; Fetching podspec for `image_crop` from `.symlinks/plugins/image_crop/ios`     -&gt; Fetching podspec for `image_picker` from     `.symlinks/plugins/image_picker/ios`     -&gt; Fetching podspec for `path_provider` from     `.symlinks/plugins/path_provider/ios`     -&gt; Fetching podspec for `path_provider_macos` from     `.symlinks/plugins/path_provider_macos/ios`     -&gt; Fetching podspec for `permission_handler` from     `.symlinks/plugins/permission_handler/ios`     -&gt; Fetching podspec for `shared_preferences` from     `.symlinks/plugins/shared_preferences/ios`     -&gt; Fetching podspec for `shared_preferences_macos` from     `.symlinks/plugins/shared_preferences_macos/ios`     -&gt; Fetching podspec for `shared_preferences_web` from     `.symlinks/plugins/shared_preferences_web/ios`     -&gt; Fetching podspec for `tencent_im_plugin` from     `.symlinks/plugins/tencent_im_plugin/ios`     -&gt; Fetching podspec for `webview_flutter` from     `.symlinks/plugins/webview_flutter/ios`     Resolving dependencies of `Podfile`       CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local       because checking is only perfomed in repo update       CDN: trunk Relative path: all_pods_versions_8_f_f.txt exists! Returning       local because checking is only perfomed in repo update       CDN: trunk Relative path:       Specs/8/f/f/AMapFoundation/1.6.2/AMapFoundation.podspec.json exists!       Returning local because checking is only perfomed in repo update       CDN: trunk Relative path: all_pods_versions_0_3_9.txt exists! Returning       local because checking is only perfomed in repo update       CDN: trunk Relative path:       Specs/0/3/9/AMapLocation/2.6.4/AMapLocation.podspec.json exists! Returning       local because checking is only perfomed in repo update       CDN: trunk Relative path: all_pods_versions_6_1_0.txt exists! Returning       local because checking is only perfomed in repo update       CDN: trunk Relative path:       Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json exists! Returning       local because checking is only perfomed in repo update       CDN: trunk Relative path: all_pods_versions_8_d_3.txt exists! Returning       local because checking is only perfomed in repo update     [!] Unable to find a specification for `HandyJSON` depended upon by     `tencent_im_plugin`     You have either:      * out-of-date source repos which you can update with `pod repo update` or      with `pod install --repo-update`.      * mistyped the name or version.      * not added the source repo that hosts the Podspec to your Podfile.     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:389:     in `find_cached_set'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:     in `specifications_for_dependency'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:     in `search_for'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:     in `block in sort_dependencies'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:     in `each'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:     in `sort_by'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:     in `sort_dependencies'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif     ication_provider.rb:53:in `block in sort_dependencies'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif     ication_provider.rb:70:in `with_no_such_dependency_error_handling'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specif     ication_provider.rb:52:in `sort_dependencies'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:75     4:in `push_state_for_requirements'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:74     6:in `require_nested_dependencies_for'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:72     9:in `activate_new_spec'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:68     6:in `attempt_to_activate'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:25     4:in `process_topmost_state'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:18     2:in `resolve'     /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:i     n `resolve'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:i     n `resolve'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz     er.rb:1065:in `block in resolve_dependencies'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r     b:64:in `section'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz     er.rb:1063:in `resolve_dependencies'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyz     er.rb:124:in `analyze'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410     :in `analyze'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235     :in `block in resolve_dependencies'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.r     b:64:in `section'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234     :in `resolve_dependencies'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156     :in `install!'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.     rb:52:in `run'     /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in     `run'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in     `run'     /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top     (required)&gt;'     /usr/local/bin/pod:22:in `load'     /usr/local/bin/pod:22:in `<main&gt;' Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies. To update the CocoaPods specs, run:   pod repo update Error running pod install Error launching application on iPhone 11 Pro Max.
